// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzfubwovdffjavvkosqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZnVid292ZGZmamF2dmtvc3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjE5NjcsImV4cCI6MjA3MDc5Nzk2N30.Y7dh-dfWm1kAAu7UHFuMSGfIN8Vc4UKdD4RpBLqIuJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});